### ISSUE TITLE
Swapping version after selecting model shows blank page

### ISSUE THREAD

**Issue by mweinelt** [mwarning/yet-another-firmware-selector#57]
Selecting a version and model shows the firmware. Swapping out the version gets you a blank page until you reconfirm the model, although the model string is still there.

**Comment by mwarning** [comment]
Can you provide an example (and the link you were using)? I just tried "TP-Link TL-WDR4300 v1" and switched the version/release. The entry was uploaded.

**Comment by mweinelt** [comment]
Ah, I tried the R7800. Between 19.07 and master the target name changed from `ipq806x` to `ipq806x-generic` IIRC, so that's a special case.

**Comment by mwarning** [comment]
There were a lot of name changes (aka cleanup) between 19.07 and master. There is also the ar71xx to ath79 transition. Theses things are causing problems right now.

I particular, I see "Netgear Nighthawk X4S R7800"  19.07.4 and "NETGEAR Nighthawk X4S R7800" for master. The code does not use fuzzy matching when the version is switched. This is the problem here.

I will look into the problem later.

**Comment by mwarning** [comment]
Fixed. The model should stay selected when a different version is selected (given the device id or device title stay the same between versions/releases).
